baseURL = '/'
languageCode = 'en-us'
title = 'Dory Alexander'
theme = 'cactus'
# Main menu which appears below site header.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  showAllPostsArchive = false # default

  # Home page settings
  description = "Securing the Cloud, Fueled by a Passion for Technology, Food, Travel, and Adventure"

# the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/dalexanderio"
  [[params.social]]
    name = "email"
    link = "dory@dalexander.io"  # no need for "mailto:" in the head

